package com.config;


import javax.sql.DataSource;

import org.springframework.boot.jdbc.DataSourceBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import com.netflix.config.DynamicConfiguration;
import com.netflix.config.DynamicPropertyFactory;
import com.netflix.config.DynamicStringProperty;
import com.netflix.config.FixedDelayPollingScheduler;
import com.netflix.config.sources.JDBCConfigurationSource;



@RestController

public class ReadConfigFromJDBCController {

	

	
	ReadConfigFromJDBCController(){
		setupJDBC();
	}
	
	@Bean
	public void setupJDBC() {
        DataSource ds = getDataSource();

        try {
            JDBCConfigurationSource source = new JDBCConfigurationSource(
                    ds,
                    "select distinct property_key, property_value from MySiteProperties",
                    "property_key", "property_value");
            FixedDelayPollingScheduler scheduler = new FixedDelayPollingScheduler(
                    0, 10, false);
            DynamicConfiguration configuration = new DynamicConfiguration(source,
                    scheduler);
            DynamicPropertyFactory.initWithConfigurationSource(configuration);
     
          
        } catch (Exception e) {
            //Clean up the data files generated by the embedded DB.
        }

	}
	
	@GetMapping("/ReadJDBCConfigProperty")
	public String ReadConfigFile() {
		
		  DynamicStringProperty prop1 = DynamicPropertyFactory.getInstance().getStringProperty(
                  "prop1", "default");
          System.out.println("value1"+ prop1.get());
          
		return prop1.get();
	}
	
	@Bean
	public DataSource getDataSource() { 
	   
		 DriverManagerDataSource dataSource = new DriverManagerDataSource();
	        dataSource.setDriverClassName("org.h2.Driver");
	        dataSource.setUrl("jdbc:h2:file:~/data/config");
	        dataSource.setUsername("sa");
	        dataSource.setPassword("");
	        return dataSource;
		
	}
	
	
	
}
